import type { Localized } from './i18n'
export type StreamId = 'C' | 'D' | 'LM' | 'LO' | 'TMGM'
export type Exercise = { id: string; difficulty: 1 | 2 | 3; duration: number; question: Localized; hint: Localized; answer: Localized; correction: Localized }
export type Chapter = { id: string; title: Localized; duration: number; summary: Localized; prerequisites: Localized[]; objectives: Localized[]; essentials: Localized[]; method: Localized[]; example: Localized; mistakes: Localized[]; recap: Localized; exercises: Exercise[] }
export type Subject = { id: string; name: Localized; short: string; coefficient: number; chapters: Chapter[] }
export type Stream = { id: StreamId; name: Localized; description: Localized; subjects: Subject[] }
const l=(fr:string,ar:string):Localized=>({fr,ar})
const chapter=(id:string,title:Localized,summary:Localized,key:Localized,q:Localized,a:Localized):Chapter=>({id,title,duration:40,summary,prerequisites:[l('Vocabulaire de base du thème','المصطلحات الأساسية للمحور'),l('Calculs et lecture attentive de l’énoncé','الحساب والقراءة الدقيقة للسؤال')],objectives:[l(`Expliquer ${title.fr.toLowerCase()} avec précision`,`شرح ${title.ar} بدقة`),l('Choisir une méthode adaptée à une question de BAC','اختيار المنهجية المناسبة لسؤال البكالوريا'),l('Justifier chaque étape de la réponse','تبرير كل خطوة في الإجابة')],essentials:[key,summary,l('Une réponse gagne des points quand elle définit, applique puis conclut.','تحصل الإجابة على نقاط عندما تعرّف وتطبّق ثم تستنتج.')],method:[l('Repérer les données, le verbe de consigne et ce qui est demandé.','حدّد المعطيات وفعل التعليمة والمطلوب.'),l('Rappeler la règle ou le concept utile avant de l’appliquer.','اكتب القاعدة أو المفهوم المناسب قبل التطبيق.'),l('Dérouler les étapes sans saut et contrôler unités ou preuves.','أنجز الخطوات دون قفز وتحقق من الوحدات أو الأدلة.'),l('Rédiger une conclusion qui répond exactement à la question.','اكتب استنتاجا يجيب مباشرة عن السؤال.')],example:l(`Exemple guidé : ${q.fr} Solution : ${a.fr}`,`مثال موجه: ${q.ar} الحل: ${a.ar}`),mistakes:[l('Donner seulement le résultat sans justification.','كتابة النتيجة دون تبرير.'),l('Utiliser une règle sans vérifier ses conditions.','استعمال قاعدة دون التحقق من شروطها.'),l('Négliger la conclusion ou les unités.','إهمال الاستنتاج أو الوحدات.')],recap:l(`${title.fr} : retiens la notion clé, la méthode en quatre étapes et entraîne-toi sans regarder la solution.`,`${title.ar}: احفظ الفكرة الأساسية والمنهجية ذات الخطوات الأربع ثم تدرّب دون النظر إلى الحل.`),exercises:[{id:`${id}-1`,difficulty:1,duration:10,question:q,hint:l('Identifie la règle dans les notions essentielles.','ابحث عن القاعدة في المفاهيم الأساسية.'),answer:a,correction:l(`On identifie la donnée utile, on applique la règle du chapitre, puis on obtient : ${a.fr}`,`نحدّد المعطى المناسب ونطبّق قاعدة الفصل فنحصل على: ${a.ar}`)},{id:`${id}-2`,difficulty:2,duration:15,question:l(`Explique la méthode de ${title.fr} et construis un exemple personnel.`,`اشرح منهجية ${title.ar} وقدّم مثالا من إنشائك.`),hint:l('Utilise : définition, règle, application, conclusion.','استعمل: التعريف، القاعدة، التطبيق، الاستنتاج.'),answer:l('La réponse doit présenter la notion, une règle correcte, un exemple traité et une conclusion.','يجب أن تتضمن الإجابة المفهوم وقاعدة صحيحة ومثالا محلولا واستنتاجا.'),correction:l(`Une bonne production définit d’abord ${title.fr}, applique ensuite ${key.fr.toLowerCase()}, puis vérifie le résultat.`,`تبدأ الإجابة الجيدة بتعريف ${title.ar} ثم تطبّق ${key.ar} وتتحقق من النتيجة.`)}]})
const bank:Record<string,Chapter[]>={
maths:[chapter('math-limits',l('Limites et continuité','النهايات والاتصال'),l('Étudier le comportement local et asymptotique d’une fonction.','دراسة سلوك الدالة محليا وعند اللانهاية.'),l('Une fonction dérivable sur un intervalle y est continue.','كل دالة قابلة للاشتقاق على مجال فهي متصلة عليه.'),l('Calculer la limite de (2x²−3x+1)/x² en +∞.','احسب نهاية (2x²−3x+1)/x² عند +∞.'),l('En divisant par x², la limite vaut 2.','بقسمة الحدود على x² تكون النهاية 2.')),chapter('math-complex',l('Nombres complexes','الأعداد العقدية'),l('Utiliser les formes algébrique et trigonométrique.','استعمال الصيغتين الجبرية والمثلثية.'),l('La formule de Moivre permet de calculer les puissances.','تسمح صيغة موافر بحساب القوى.'),l('Résoudre z²+1=0 dans ℂ.','حل z²+1=0 في ℂ.'),l('z=i ou z=−i.','z=i أو z=−i.')),chapter('math-proba',l('Probabilités','الاحتمالات'),l('Modéliser une expérience et utiliser les probabilités conditionnelles.','نمذجة تجربة واستعمال الاحتمالات الشرطية.'),l('P(A∩B)=P(A)×P(B|A).','P(A∩B)=P(A)×P(B|A).'),l('Probabilité d’obtenir 3 piles en 3 lancers équilibrés ?','ما احتمال الحصول على الصورة ثلاث مرات في ثلاث رميات؟'),l('(1/2)³=1/8.','(1/2)³=1/8.'))],
physics:[chapter('phy-mech',l('Mécanique','الميكانيكا'),l('Appliquer les lois de Newton à un système isolé.','تطبيق قوانين نيوتن على جملة معزولة.'),l('ΣF⃗=m·a⃗ dans un référentiel galiléen.','ΣF⃗=m·a⃗ في مرجع غاليلي.'),l('Une masse de 2 kg subit 6 N. Calculer a.','كتلة 2 kg تؤثر عليها قوة 6 N. احسب التسارع.'),l('a=F/m=3 m·s⁻².','a=F/m=3 m·s⁻².')),chapter('phy-elec',l('Circuits électriques','الدوائر الكهربائية'),l('Analyser les régimes des dipôles RC et RL.','تحليل نظامي ثنائي القطب RC وRL.'),l('Pour un condensateur q=C·u.','بالنسبة للمكثف q=C·u.'),l('Charge de 10 μF sous 12 V ?','شحنة مكثف 10 μF تحت توتر 12 V؟'),l('q=120 μC.','q=120 μC.')),chapter('phy-waves',l('Ondes et optique','الموجات والبصريات'),l('Caractériser propagation et interférences.','وصف الانتشار والتداخل.'),l('v=λf.','v=λf.'),l('f=50 Hz et λ=2 m. Calculer v.','f=50 Hz وλ=2 m. احسب v.'),l('v=100 m·s⁻¹.','v=100 m·s⁻¹.'))],
svt:[chapter('svt-genetics',l('Génétique','الوراثة'),l('Relier gènes, expression et diversité.','ربط المورثات بالتعبير والتنوع.'),l('Un allèle est une version d’un gène.','الأليل نسخة من المورثة.'),l('Croisement Aa×Aa : proportion de aa ?','تهجين Aa×Aa: ما نسبة aa؟'),l('1/4.','1/4.')),chapter('svt-immunity',l('Immunologie','علم المناعة'),l('Distinguer immunité innée et adaptative.','التمييز بين المناعة الفطرية والمكتسبة.'),l('La mémoire accélère la réponse secondaire.','تسرّع الذاكرة الاستجابة الثانوية.'),l('Pourquoi un vaccin protège-t-il ?','لماذا يحمي اللقاح؟'),l('Il forme des cellules mémoire contre un antigène.','يُكوّن خلايا ذاكرة ضد مولد الضد.'))],
arabic:[chapter('ar-text',l('Analyse du texte littéraire','تحليل النص الأدبي'),l('Construire une lecture fondée sur les idées, procédés et preuves.','بناء قراءة قائمة على الأفكار والأساليب والشواهد.'),l('Introduction, analyse avec citations, synthèse.','مقدمة وتحليل بالشواهد ثم خلاصة.'),l('Dégage l’idée d’un texte appelant à rechercher le savoir.','حدّد فكرة نص يدعو إلى طلب العلم.'),l('La valeur du savoir dans le progrès individuel et collectif.','قيمة العلم في تقدم الفرد والمجتمع.')),chapter('ar-grammar',l('Grammaire et morphologie arabes','النحو والصرف'),l('Appliquer l’analyse grammaticale et les transformations.','تطبيق الإعراب والتحويلات الصرفية.'),l('L’analyse dépend de la fonction du mot.','يعتمد الإعراب على موقع الكلمة.'),l('أعرب «العلمُ» في: العلمُ نورٌ.','أعرب «العلمُ» في: العلمُ نورٌ.'),l('العلمُ: مبتدأ مرفوع بالضمة.','العلمُ: مبتدأ مرفوع بالضمة.'))],
french:[chapter('fr-argument',l('Texte argumentatif','النص الحجاجي'),l('Identifier thèse, arguments et connecteurs.','تحديد الأطروحة والحجج والروابط.'),l('Une idée et une preuve par paragraphe.','فكرة ودليل في كل فقرة.'),l('Donne une thèse sur l’utilité de la lecture.','قدّم أطروحة حول فائدة القراءة.'),l('La lecture développe vocabulaire et pensée critique.','تنمي القراءة الرصيد اللغوي والتفكير النقدي.')),chapter('fr-summary',l('Résumé et synthèse','التلخيص والتركيب'),l('Réduire un texte avec fidélité et cohérence.','اختصار النص بأمانة وترابط.'),l('Conserver l’ordre des idées sans copier.','الحفاظ على ترتيب الأفكار دون نسخ.'),l('Résume : « Le sport renforce le corps et la discipline. »','لخص: الرياضة تقوي الجسم والانضباط.'),l('Le sport développe santé et discipline.','تنمي الرياضة الصحة والانضباط.'))],
english:[chapter('en-reading',l('Reading comprehension','فهم المقروء بالإنجليزية'),l('Locate evidence and infer meaning.','استخراج الدليل واستنتاج المعنى.'),l('Read the question, then scan for evidence.','اقرأ السؤال ثم ابحث عن الدليل.'),l('Change to passive: Students revise lessons.','حوّل للمبني للمجهول: Students revise lessons.'),l('Lessons are revised by students.','Lessons are revised by students.')),chapter('en-writing',l('Guided writing','الكتابة الموجهة بالإنجليزية'),l('Plan connected ideas and a conclusion.','تنظيم أفكار مترابطة وخاتمة.'),l('Use linking words accurately.','استعمل أدوات الربط بدقة.'),l('Write a sentence with “therefore”.','اكتب جملة باستعمال therefore.'),l('Education creates opportunities; therefore, it matters.','Education creates opportunities; therefore, it matters.'))],
philosophy:[chapter('philo-dissertation',l('La dissertation','المقال الفلسفي'),l('Problématiser, argumenter et discuter.','بناء الإشكال والحجاج والمناقشة.'),l('La problématique transforme le sujet en tension.','يحوّل الإشكال الموضوع إلى توتر فكري.'),l('Problématise : « La liberté a-t-elle des limites ? »','صغ إشكالا: هل للحرية حدود؟'),l('Les limites empêchent-elles la liberté ou la rendent-elles commune ?','هل تمنع الحدود الحرية أم تجعلها ممكنة للجميع؟')),chapter('philo-truth',l('Vérité et raison','الحقيقة والعقل'),l('Distinguer opinion, croyance et démonstration.','التمييز بين الرأي والاعتقاد والبرهان.'),l('Une affirmation rationnelle doit être justifiée.','يجب تبرير القول العقلاني.'),l('Pourquoi une opinion vraie n’est-elle pas un savoir ?','لماذا لا يكون الرأي الصحيح معرفة؟'),l('Elle peut être vraie par hasard sans justification.','قد تصدق مصادفة دون تبرير.'))],
history:[chapter('hist-decolon',l('Décolonisation','تصفية الاستعمار'),l('Comprendre acteurs et trajectoires des indépendances.','فهم الفاعلين ومسارات الاستقلال.'),l('Relier événement, causes et conséquences.','ربط الحدث بأسبابه ونتائجه.'),l('Cite deux facteurs après 1945.','اذكر عاملين بعد 1945.'),l('Affaiblissement colonial et mouvements nationalistes.','ضعف القوى الاستعمارية وصعود الحركات الوطنية.')),chapter('geo-global',l('Mondialisation','العولمة'),l('Analyser flux, pôles et inégalités.','تحليل التدفقات والأقطاب والتفاوتات.'),l('Un croquis exige titre et légende organisée.','يتطلب الرسم عنوانا ومفتاحا منظما.'),l('Définis un flux mondial.','عرّف التدفق العالمي.'),l('Déplacement de personnes, biens, capitaux ou informations.','انتقال الأشخاص أو السلع أو الأموال أو المعلومات.'))],
islamic:[chapter('islam-values',l('Valeurs islamiques','القيم الإسلامية'),l('Relier les valeurs au comportement.','ربط القيم بالسلوك.'),l('Citer le texte et expliquer son lien avec la question.','الاستدلال بالنص وشرح علاقته بالسؤال.'),l('اذكر أثراً للصدق في المجتمع.','اذكر أثراً للصدق في المجتمع.'),l('الصدق يبني الثقة ويحفظ الحقوق.','الصدق يبني الثقة ويحفظ الحقوق.'))],
economics:[chapter('eco-market',l('Marché et prix','السوق والأسعار'),l('Comprendre offre, demande et prix.','فهم العرض والطلب والسعر.'),l('Si la demande augmente, le prix tend à monter.','إذا زاد الطلب يميل السعر للارتفاع.'),l('Demande en hausse et offre stable : effet ?','زاد الطلب والعرض ثابت: ما الأثر؟'),l('Le prix d’équilibre augmente.','يرتفع سعر التوازن.')),chapter('eco-growth',l('Croissance et développement','النمو والتنمية'),l('Distinguer production et bien-être.','التمييز بين الإنتاج والرفاه.'),l('Le PIB ne mesure pas toute la qualité de vie.','لا يقيس الناتج كل جودة الحياة.'),l('Donne un indicateur autre que le PIB.','اذكر مؤشرا غير الناتج المحلي.'),l('L’IDH.','مؤشر التنمية البشرية.'))],
technology:[chapter('tech-systems',l('Systèmes techniques','الأنظمة التقنية'),l('Analyser chaînes d’information et d’énergie.','تحليل سلسلتي المعلومات والطاقة.'),l('Acquérir, traiter, communiquer ; alimenter, convertir.','الاكتساب والمعالجة والاتصال؛ التغذية والتحويل.'),l('Quel bloc transforme l’électricité en mouvement ?','أي جزء يحول الكهرباء إلى حركة؟'),l('Le bloc convertir, par le moteur.','جزء التحويل بواسطة المحرك.')),chapter('tech-drawing',l('Dessin technique','الرسم التقني'),l('Lire vues, cotations et coupes.','قراءة المساقط والأبعاد والمقاطع.'),l('Vérifier unités, échelle et vues.','تحقق من الوحدات والسلم والمساقط.'),l('À quoi sert une vue en coupe ?','ما فائدة المقطع؟'),l('À montrer les formes intérieures.','إظهار الأشكال الداخلية.'))]}
const names:Record<string,Localized>={maths:l('Mathématiques','الرياضيات'),physics:l('Physique-Chimie','الفيزياء والكيمياء'),svt:l('Sciences naturelles','العلوم الطبيعية'),arabic:l('Arabe','اللغة العربية'),french:l('Français','الفرنسية'),english:l('Anglais','الإنجليزية'),philosophy:l('Philosophie','الفلسفة'),history:l('Histoire-Géographie','التاريخ والجغرافيا'),islamic:l('Éducation islamique','التربية الإسلامية'),economics:l('Économie','الاقتصاد'),technology:l('Technologie & génie','التكنولوجيا والهندسة')}
const s=(id:string,short:string,coefficient:number):Subject=>({id,name:names[id],short,coefficient,chapters:bank[id]})
export const streams:Stream[]=[
{id:'C',name:l('Série C','شعبة الرياضيات'),description:l('Mathématiques et sciences physiques','الرياضيات والعلوم الفيزيائية'),subjects:[s('maths','MATH',9),s('physics','PC',8),s('arabic','AR',3),s('french','FR',2),s('english','EN',2),s('philosophy','PH',2),s('islamic','EI',2)]},
{id:'D',name:l('Série D','شعبة العلوم الطبيعية'),description:l('Sciences naturelles','العلوم الطبيعية'),subjects:[s('svt','SN',8),s('maths','MATH',6),s('physics','PC',6),s('arabic','AR',3),s('french','FR',2),s('english','EN',2),s('philosophy','PH',2),s('islamic','EI',2)]},
{id:'LM',name:l('Lettres modernes','الآداب العصرية'),description:l('Langues, philosophie et sciences humaines','اللغات والفلسفة والعلوم الإنسانية'),subjects:[s('arabic','AR',6),s('french','FR',5),s('philosophy','PH',5),s('history','HG',4),s('english','EN',3),s('islamic','EI',2)]},
{id:'LO',name:l('Lettres originelles','الآداب الأصلية'),description:l('Arabe, études islamiques et sciences humaines','العربية والدراسات الإسلامية والعلوم الإنسانية'),subjects:[s('arabic','AR',8),s('islamic','EI',7),s('philosophy','PH',4),s('history','HG',4),s('french','FR',2),s('english','EN',2)]},
{id:'TMGM',name:l('Technique','الشعبة التقنية'),description:l('Mathématiques, mécanique et technologie','الرياضيات والميكانيكا والتكنولوجيا'),subjects:[s('technology','TECH',9),s('maths','MATH',7),s('physics','PA',6),s('french','FR',2),s('arabic','AR',2),s('english','EN',2),s('islamic','EI',2)]}]
export const practicalGuide=[{title:l('Rappel actif','الاسترجاع النشط'),text:l('Ferme le cours et restitue les idées clés, puis compare.','أغلق الدرس واسترجع الأفكار ثم قارن.')},{title:l('Blocs ciblés','حصص مركزة'),text:l('Travaille 25 minutes, repose-toi 5 minutes.','اعمل 25 دقيقة واسترح 5 دقائق.')},{title:l('Correction intelligente','تصحيح ذكي'),text:l('Repère l’étape de l’erreur et refais l’exercice demain.','حدّد موضع الخطأ وأعد التمرين غدا.')},{title:l('Stratégie d’épreuve','استراتيجية الامتحان'),text:l('Commence par les points accessibles et garde 10 minutes pour relire.','ابدأ بالأسئلة السهلة واترك 10 دقائق للمراجعة.')}]
export const officialResources=[{title:l('Ministère de l’Éducation nationale','وزارة التهذيب الوطني'),organization:l('Gouvernement mauritanien','الحكومة الموريتانية'),url:'https://www.education.gov.mr/',language:'FR / AR',verified:'11 juillet 2026'},{title:l('Plateforme numérique Taalimi','منصة تعليمي الرقمية'),organization:l('Ressources éducatives mauritaniennes','موارد تعليمية موريتانية'),url:'https://taalimi.info/',language:'FR / AR',verified:'11 juillet 2026'}]
export const sourceNote=l('Ces fiches sont des contenus pédagogiques originaux structurés à partir de thèmes publics. Les coefficients et intitulés doivent être confirmés auprès de votre établissement.','هذه ملخصات تربوية أصلية مبنية على محاور منشورة. يجب تأكيد المعاملات والعناوين لدى مؤسستك.')
