const { Client } = require('pg')
const fs = require('fs')
const url = fs.readFileSync('.env.local','utf8').split(/\r?\n/).find(l=>l.startsWith('DATABASE_URL=')).slice('DATABASE_URL='.length).trim().replace(/^"/, '').replace(/"$/, '')
const c = new Client({ connectionString: url, ssl: { rejectUnauthorized: false } })
c.connect()
  .then(() => c.query(fs.readFileSync('schema.sql','utf8')))
  .then(() => c.query("SELECT table_name FROM information_schema.tables WHERE table_schema='public'"))
  .then(r => { console.log('tables:', JSON.stringify(r.rows)); return c.end() })
  .catch(e => { console.error('ERR', e.message); process.exit(1) })
